# Generated by Django 3.1.2 on 2020-10-31 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201030_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='menu',
            new_name='category',
        ),
    ]
