# Generated by Django 3.1.2 on 2020-11-01 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201031_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritions',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
