# Generated by Django 3.1.2 on 2020-11-01 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='sizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('size_name', models.CharField(blank=True, max_length=20, null=True)),
                ('size_ml', models.IntegerField()),
                ('nutrition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.nutritions')),
            ],
        ),
    ]
