# Generated by Django 3.1.2 on 2020-11-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_sizes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sizes',
            old_name='size_name',
            new_name='size_fluid_ounce',
        ),
        migrations.AlterField(
            model_name='sizes',
            name='size_ml',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
